export const HeroConstants = {
	FETCH_ALL: 'FETCH_ALL',
	REMOVE_ALL: 'REMOVE_ALL',
	FETCH_ALL_ERROR: 'FETCH_ALL_ERROR',
	FETCH_ALL_SUCCESS: 'FETCH_ALL_SUCCESS'
};

export const MMRConstants = {
	FETCH_COUNTRIES: 'FETCH_COUNTRIES',
	FETCH_COUNTRIES_SUCCESS: 'FETCH_COUNTRIES_SUCCESS',
	FETCH_COUNTRIES_ERROR: 'FETCH_COUNTRIES_ERROR'
};

export const Common = {
	SHIT_HAPPEN: 'SHIT_HAPPEN'
};